name: swh_transformers
channels:
  - conda-forge
dependencies:
  - pytest
  - fairscale
  - transformers
  - tokenizers
  - ipython
  - pandas
  - pytorch-gpu
  - cudatoolkit>11
  - python<3.10,>=3.9
